### PR TITLE
Make palemoon 27.4.2 compiling

### PR DESCRIPTION
**Pull request by nado**
Hi.

I’ve made a few changes in order to get PM to compile on my system : 

* Fix gcc version checking in palemoon-2.eclass by using toolchain-funcs
* Rename OBJDIR in order to reduce its char length as stated in https://github.com/deuiore/palemoon-overlay/issues/37#issuecomment-318093218
* Adding a patch to fix the issue described here https://github.com/MoonchildProductions/Pale-Moon/issues/1324
* Repoman warning cleaning (stale cvs headers, missing metadata about use flags)

I haven’t tested L10N.
I am unsure about the bash code used here https://github.com/deuiore/palemoon-overlay/commit/417bd76875a8586982cf608007b363100275565b#diff-cdcd378a53d25c465f1edb0fc1a5b0f5R19 so any comments would be appreciated.

### CODE REVIEW

**Comment by buzden** [comment]
Localization (at least, Russian) definitely does not work because the original manifest has bad digests (actually, l10n files were updated after the digests calculation, this is not your fault, of course).

**Comment by nado** [comment]
Alright, I’ll download them and recalculate digests in a few hours.

**Comment by deuiore** [comment]
Thanks for your help!
Everything looks good.

I'm just going to tweak the wrong GCC version error message a little bit later. Anyway, merging it.

**Comment by thunderrd** [comment]
OK guys, works for me.

Thanks for the effort, I knew you would clear it up eventually.

**Comment by deuiore** [comment]
I don't really want to do that until GCC 5 (or what will be the main compiler then) is supported by Pale Moon.
I'm still testing every version with it to see if I experience any crashes. So far it always happened.

**Pull request merged**
